name = "CodecBzip2"
uuid = "523fee87-0ab8-5b00-afb7-3ecf72e48cfd"
license = "MIT"
authors = ["Kenta Sato <bicycle1885@gmail.com>"]
version = "0.8.2"

[deps]
Bzip2_jll = "6e34b625-4abd-537c-b88f-471c36dfa7a0"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
TranscodingStreams = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"

[compat]
Bzip2_jll = "1.0.8"
TranscodingStreams = "0.9, 0.10"
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[targets]
test = ["Test", "Random"]
